---
- include_vars: "{{ survey_path }}"

- name: template survey json
  template:
    src: survey_template.json.j2
    dest: "{{ temp_dir}}/survey_template.json"
    mode: '0777'

- name: create survey
  uri:
    url: "{{ awx_url }}/api/v2/job_templates/{{ template_id }}/survey_spec/"
    method: POST
    force_basic_auth: yes
    user: "{{ awx_user }}"
    password: "{{ awx_password }}"
    body_format: json
    body: "{{ lookup('file', '{{temp_dir }}/survey_template.json') }}"
    status_code: 200, 201, 400
  register: survey_response

- name: status code 201 or 200
  debug:
    msg: " Survey created successfully"
  when: survey_response.status == 201 or survey_response.status == 200

- name: status code 400
  block:

    - name: get response message
      set_fact:
        response_message: "{{ survey_response.json }}"

    - name: adjust for when project already exists
      block:
        - debug:
            msg: "{{ response_message.__all__ }} Task will continue anyway"

      when: response_message.__all__ is defined and response_message.__all__ is search('already exists')

    - fail:
        msg: "{{ response_message }}"
      when: response_message.__all__ is not defined or ((response_message.__all__ is search('already exists')) != True)

  when: response.status == 400


