---
- name: get template vars with surveys
  block:
    - name: get path for template vars
      find:
        path: "{{ path }}"
      register: paths
  when: with_survey == True

- include_vars: "{{ template_path }}"
  vars:
    path_list: "{% if with_survey == True is defined %}{{paths.files | map(attribute='path') | list }}{% else %}{% endif %}"
    template_path: '{% if with_survey == False %}{{ path }}{% elif paths is defined %}{{ path_list | select("match", "_template\.yml") | list |first }}{% else %}{% endif %}'

- name: create job_template
  block:
    - name: template job_template
      template:
        src: jobTemplate_template.json.j2
        dest: "{{ temp_dir }}/jobTemplate_template.json"
        mode: '0777'

    - name: API request to create job template
      uri:
        url: "{{ awx_url }}/api/v2/job_templates/"
        method: POST
        force_basic_auth: yes
        user: "{{ awx_user }}"
        password: "{{ awx_password }}"
        body_format: json
        body: "{{ lookup('file', '{{ temp_dir }}/jobTemplate_template.json') }}"
        status_code: 201, 400
      register: response
      until: response.status == 201 or (response.json.__all__ is defined and response.json.__all__ is search('already exists'))
      retries: 5
      delay: 10
  vars:
    inventory_id: "{{ inventories | json_query(\"json.results[?name=='\" + template.inventory + \"'].id\") | first }}"

- name: get template_id on status code 400
  block:
    - name: adjust for when project already exists
      block:
        - debug:
            msg: "{{ response_message.__all__ }} Task will continue anyway"

        - name: List templates
          uri:
            url: "{{ awx_url }}/api/v2/job_templates/"
            method: GET
            force_basic_auth: yes
            user: "{{ awx_user }}"
            password: "{{ awx_password }}"
          register: tmps

      when: response_message.__all__ is defined and response_message.__all__ is search('already exists')

    - fail:
        msg: "{{ response_message }}"
      when: response_message.__all__ is not defined or ((response_message.__all__ is search('already exists')) != True)

  when: response.status == 400
  vars:
    response_message: "{{ info.json }}"

- name: create survey when it's defined
  include_tasks: create_survey.yml
  when: with_survey == True
  vars:
    path_list: "{% if paths is defined %}{{paths.files | map(attribute='path') | list }}{% else %}{% endif %}"
    template_id: "{% if response.status == 201 %}{{response.jsone.id}}{% elif tmps is defined %}{{ tmps | json_query(\"json.results[?name=='\" + template.name + \"'].id\") | first }}{% else %}{% endif %}"
    survey_path: '{% if paths is defined %}{{ path_list | select("match", "_survey\.yml") | list |first }}{% else %}{% endif %}'
