---
- name: consume service.yml
  include_vars: service.yml

- name: get contents of template folder
  find:
    path: "{{ template_directory }}"
  register: template_contents
  when: template_directory is defined and template_directory != ""

- set_fact:
    template_config_paths: "{{ template_contents.files | map(attribute='path') | list }}"
  when: template_contents is defined

- fail:
    msg: "Please set the awx_url variable and try again"
  when: awx_url is not defined

- name: set temp_dir
  set_fact:
    temp_dir: /tmp/awx

- name: create temporary directory
  file:
    path: "{{ temp_dir }}/"
    state: directory
    mode: '0777'

- name: Create project
  include_tasks: create_project.yml
